package com.abc;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.junit.jupiter.api.Test;

public class AccountNumberTest {
	
	/**
	 * All account numbers should be unique
	 * I chose to have a 6 digit number, so the range is 100000 - 999999
	 */
	@Test
	public void account_numbers_are_unique() {
		
		// We populate a list with the all numbers generated by account number generator
		List<Integer> accountNumbers = new ArrayList<Integer>();
		AccountNumber accs = new AccountNumber();
		for (int i=0; i<899999; i++)
			accountNumbers.add(accs.generateAccountNumber());
		
		// We copy numbers into a set
		Set<Integer> set = new HashSet<Integer>(accountNumbers);
		
		// If the set had less, it would show we had duplicates
		assertEquals(accountNumbers.size(), set.size());
	}
}
